name: Publish Site
run-name: Runs the site publish action for ${{ github.event.inputs.environment }}

on:
  workflow_dispatch:
    inputs:
      site_label:
        type: choice
        description: 'Select which site to publish'
        options:
        - webflow-copy.deriv.com
        - pretend-site.webflow.io
        required: true

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Map site label to site ID
      id: map-site-id
      run: |
        echo "Mapping site label to site ID"
        case "${{ github.event.inputs.site_label }}" in
          "webflow-copy.deriv.com") SITE_ID="65cf252c355bb0ab87269e04" ;;
          "pretend-site.webflow.io") SITE_ID="I_HAVE_NO_SITE_ID" ;;
          *) echo "Invalid site label"; exit 1 ;;
        esac
        echo "::set-output name=site_id::$SITE_ID"

    - name: Trigger Webflow Publish
      env:
        WEBFLOW_API_TOKEN: ${{ secrets.WEBFLOW_API_TOKEN }}
        SITE_TO_DEPLOY: ${{ steps.map-site-id.outputs.site_id }}
        SITE_ID: "65cf252c355bb0ab87269e04"
      run: |
        curl -X POST "https://api.webflow.com/v2/sites/$SITE_ID/publish" \
        -H "Authorization: Bearer $WEBFLOW_API_TOKEN" \
        -H "Accept: application/json" \
        -H "Content-Type: application/json" \
        -d "{
              \"publishToWebflowSubdomain\": false,
              \"customDomains\": [
                \"$SITE_TO_DEPLOY\"
              ]
            }"
