name: Publish Site
run-name: Runs the site publish action for ${{ github.event.inputs.environment }}

on:
  workflow_dispatch:
    inputs:
      site_label:
        type: choice
        description: 'Select which site to publish'
        options:
        - webflow-copy.deriv.com
        - pretend-site.webflow.io
        required: true

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Map site label to site ID
      id: map-site-id
      run: |
        echo "Mapping site label to site ID"
        case "${{ github.event.inputs.site_label }}" in
          "webflow-copy.deriv.com") SITE_TO_DEPLOY="65fad28eed7a6248275d2fe7" ;;
          "pretend-site.webflow.io") SITE_TO_DEPLOY="I_HAVE_NO_SITE_ID" ;;
          *) echo "Invalid site label"; exit 1 ;;
        esac
        echo "site_to_deploy=$SITE_TO_DEPLOY" >> $GITHUB_OUTPUT

    - name: Trigger Webflow Publish
      env:
        WEBFLOW_API_TOKEN: ${{ secrets.WEBFLOW_API_TOKEN }}
        SITE_TO_DEPLOY: ${{ steps.map-site-id.outputs.site_to_deploy }}
        SITE_ID: "65cf252c355bb0ab87269e04"
      run: |
        RESPONSE=$(curl -s -o response.txt -w "%{http_code}" -X POST "https://api.webflow.com/v2/sites/$SITE_ID/publish" \
          -H "Authorization: Bearer $WEBFLOW_API_TOKEN" \
          -H "Accept: application/json" \
          -H "Content-Type: application/json" \
          -d "{
                \"publishToWebflowSubdomain\": false,
                \"customDomains\": [
                  \"$SITE_TO_DEPLOY\"
                ]
              }")
        if [ $RESPONSE -ne 200 ]; then
          echo "Webflow Publish failed with status $RESPONSE"
          cat response.txt
          exit 1
        else
          echo "Webflow Publish succeeded"
        fi
