name: Publish Site
run-name: Runs the site publish action for multiple domains

on:
  workflow_dispatch:
    inputs:
      site_label_staging_webflow:
        type: boolean
        description: 'staging-webflow.deriv.com'
        default: false
      site_label_deriv_com:
        type: boolean
        description: 'deriv.com'
        default: false
      site_label_deriv_me:
        type: boolean
        description: 'deriv.me'
        default: false
      site_label_deriv_be:
        type: boolean
        description: 'deriv.be'
        default: false

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Map site labels to site IDs and deploy
        id: map-site-ids
        env:
          WEBFLOW_API_TOKEN: ${{ secrets.WEBFLOW_API_TOKEN }}
          SITE_ID: ${{ secrets.SITE_ID }}
        run: |
          SITES_TO_PUBLISH=()
          if [ "${{ github.event.inputs.site_label_staging_webflow }}" == "true" ]; then
            SITES_TO_PUBLISH+=("staging-webflow.deriv.com")
          fi
          if [ "${{ github.event.inputs.site_label_deriv_com }}" == "true" ]; then
            SITES_TO_PUBLISH+=("deriv.com")
          fi
          if [ "${{ github.event.inputs.site_label_deriv_me }}" == "true" ]; then
            SITES_TO_PUBLISH+=("deriv.me")
          fi
          if [ "${{ github.event.inputs.site_label_deriv_be }}" == "true" ]; then
            SITES_TO_PUBLISH+=("deriv.be")
          fi
            SITES_ARRAY="[$(IFS=,; echo "${SITES_TO_PUBLISH[*]}")]"  
            echo "Publishing to $site"
            RESPONSE=$(curl -s -o response_${site//./_}.txt -w "%{http_code}" -X POST "https://api.webflow.com/v2/sites/$SITE_ID/publish" \
              -H "Authorization: Bearer $WEBFLOW_API_TOKEN" \
              -H "Accept: application/json" \
              -H "Content-Type: application/json" \
              -d "{
                    \"publishToWebflowSubdomain\": false,
                    \"customDomains\": $SITES_ARRAY,
                  }")
            if [ $RESPONSE -ne 202 ]; then
              echo "Webflow Publish to $site failed with status $RESPONSE"
              cat response_${site//./_}.txt
              exit 1
            else
              echo "Webflow Publish to $site succeeded"
            fi
  send_slack_success:
        name: Send Release Slack notification success
        runs-on: ubuntu-latest
        if: success()
        needs: [publish]
        steps:
          - name: Send Slack Notification
            uses: "deriv-com/shared-actions/.github/actions/send_slack_notification@master"
            with:
              SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
              MESSAGE: "Release succeeded for ${SITES_TO_PUBLISH} with version ${{ needs.build_test_and_publish.outputs.RELEASE_VERSION }}"
    
