name: Create Sitemap.xml and robots.txt for all the domains and Upload to R2

on:
  workflow_call:
    inputs:
      site_label_staging_webflow:
        type: boolean
        description: "staging-webflow.deriv.com"
        default: false
      site_label_webflow:
        type: boolean
        description: "webflow.deriv.com"
        default: false
      site_label_deriv_com:
        type: boolean
        description: "deriv.com"
        default: false
      site_label_deriv_me:
        type: boolean
        description: "deriv.me"
        default: false
      site_label_deriv_be:
        type: boolean
        description: "deriv.be"
        default: false

jobs:
  update-sitemap-and-robots:
    runs-on: ubuntu-latest
    env:
      BASE_DOMAIN: https://staging-webflow.deriv.com
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"
      - name: Install yargs
        run: npm install yargs

      - name: Download sitemap.xml
        run: |
          curl -O $BASE_DOMAIN/sitemap.xml -O $BASE_DOMAIN/robots.txt

      - name: Replace sitemap URLs and create directories
        env:
          MAIN_DOMAIN: "https://deriv.com"
        run: |
          echo "value of site_label_staging_webflow: " ${{ github.event.inputs.site_label_staging_webflow }}
          echo "value of site_label_webflow: " ${{ github.event.inputs.site_label_webflow }}
          echo "value of site_label_deriv_com: " ${{ github.event.inputs.site_label_deriv_com }}
          echo "value of site_label_deriv_me: " ${{ github.event.inputs.site_label_deriv_me }}
          echo "value of site_label_deriv_be: " ${{ github.event.inputs.site_label_deriv_be }}
          mkdir content
          domain_name=$(echo $MAIN_DOMAIN | sed 's|https://||g')
          mkdir -p content/$domain_name
          cp sitemap.xml content/$domain_name/sitemap.xml
          cp robots.txt content/$domain_name/robots.txt
          node .github/workflows/modify_sitemap.js --new-domain $domain_name --input-file content/$domain_name/sitemap.xml
          node .github/workflows/modify_robots.js --sitemap-url $domain_name --input-file content/$domain_name/robots.txt
          rm sitemap.xml robots.txt

      - name: R2 Upload Action to upload translations to Cloudflare
        uses: ryand56/r2-upload-action@latest
        with:
          r2-account-id: ${{ secrets.R2_ACCOUNT_ID }}
          r2-access-key-id: ${{ secrets.R2_ACCESS_KEY_ID }}
          r2-secret-access-key: ${{ secrets.R2_SECRET_ACCESS_KEY }}
          r2-bucket: ${{ secrets.R2_BUCKET_NAME }}
          source-dir: ./content
          destination-dir: .

  send_slack_success:
    name: Send Release Slack notification success

    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success'}}
    needs: [update-sitemap-and-robots]
    steps:
      - name: Determine Slack Message
        id: slack_message

        run: |
          DATE=$(date '+%Y-%m-%d %H:%M:%S')
          echo "Determined SITES_ARRAY: $SITES_ARRAY"
          if [ "${{ needs.update-sitemap-and-robots.result }}" == "failure" ]; then
            echo "MESSAGE=Sitemap and robots.txt failed for latest webflow release at $DATE" >> $GITHUB_ENV
          else
          fi
      - name: Send Slack Notification
        uses: "deriv-com/shared-actions/.github/actions/send_slack_notification@master"
        with:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          MESSAGE: ${{ env.MESSAGE }}
